### ISSUE TITLE
Installation of Guacamole Proxy Daemon for RPort failed

### ISSUE THREAD

**Issue by kakalpa** [cloudradar-monitoring/rportd-installer#2]
i tried installing the system but it stops at 

` SSL key and self-signed certificate created.
[-] Configuration file /etc/rport/rportd.conf written.
[-] RPort Database /var/lib/rport/user-auth.db created.
[-] Client auth file /var/lib/rport/client-auth.json written.
[*] totp-based two factor authentication installed.
[*] The RPort Frontend has been installed from the latest stable release.
[*] NoVNC already installed
[*] Going to install the Guacamole Proxy Daemon for RPort using Debian/Ubuntu Packages
[-] Downloading rport-guacamole_1.4.0_ubuntu_hirsute_x86_64.deb
curl: (22) The requested URL returned error: 404
[!] Download failed
[-] Installing rport-guacamole_1.4.0_ubuntu_hirsute_x86_64.deb via apt-get
#E: Unsupported file ./rport-guacamole_1.4.0_ubuntu_hirsute_x86_64.deb given on commandline

[!] Installation of Guacamole Proxy Daemon for RPort failed.
Status of your RPort server: NOT RUNNING
Check the logs in /var/log/rport/rportd.log

`

any help is highly appreciated

**Comment by thorstenkramm** [comment]
@kakalpa 
Ubuntu Hirsute is not supported. Please use an LTS Version (20.04 or 22.04) or execute the installer with `--skip-guacd`. RDP via browser will then be disabled.
